### ISSUE TITLE
Logo Design Offering as Open Source Contribution

### ISSUE THREAD

**Issue by anharismail** [dining-car/dining-car#1]
Hello Sir. I'm a Graphics Designer. I'm happy to see an open source project, So, I want provide a logo for you. Would you mind if I propose a new logo design for your project as my Open Source Contribution?

Thanks for the attention.

**Comment by renatolond** [comment]
Hi, Anhar!
I don't mind, but the project is in a very very initial state and the name is still a bit of a WIP. Do you mind if I hit you up in a few weeks when I have something working?

**Comment by anharismail** [comment]
That's good idea. You can reach me whenever this project has set it up. Or if you have other project which needed logo to improve the visualizations, you can tell me too.

**Comment by renatolond** [comment]
Hey, @anharismail !
If you're still interested, the name is now final and there's one instance of the project running at http://receitas.lond.com.br/ if you want to take a look to get a feel to suggest the logos.
Have a great day!

**Comment by anharismail** [comment]
Hello @renatolond . This is my logo ideas for your project. These ideas inspired from car and dining tools like spoon and fork. I take the colorway from your website.

I'm very welcome if you have any comments, opinions, or revisions. Please just tell me.

And hope you like it.

### Version 1
![DiningCar Ver  1](https://user-images.githubusercontent.com/37614260/54880155-6ccc1e00-4e74-11e9-8cbe-a4a042d86b05.png)

### Version 2
![DiningCar Ver  2](https://user-images.githubusercontent.com/37614260/54880159-781f4980-4e74-11e9-8643-b2f770199a74.png)

**Comment by renatolond** [comment]
Hey, @anharismail ! Thanks for the contributions!
The dining car in the name is related to a train's dining car https://en.wikipedia.org/wiki/Dining_car, not a real car, could you make some changes to make it more lined up with that?
Thanks again and have a good day

**Comment by anharismail** [comment]
Hi @renatolond , Thanks for your suggestion for the logo. 
Here I make some revisions about it. Please give your feedback.

![DiningCar Ver  1](https://user-images.githubusercontent.com/37614260/55222495-a323e780-523e-11e9-9eb0-d17abac34a3d.png)

**Comment by renatolond** [comment]
Hey @anharismail !
Looks good! :)

**Comment by anharismail** [comment]
Thanks for your response @renatolond , Can I add the logo to the project repository by a pull request?

**Comment by renatolond** [comment]
Yes, please do :)

**Comment by anharismail** [comment]
Hi @renatolond , I've made a pull request about the logo.

And I also provide the editable files here: https://drive.google.com/drive/u/1/folders/1WIRK-yuMkBGDAiPPV5JEHeHKTeQNLby8
